// Synthetic fixture schema. Original Prophecy IP — generated by the
// script in ./scripts/generate.ts. No third-party data is ingested;
// every fixture is procedurally minted from abstract templates so the
// engine has a 140+ card corpus to validate against (dice rolling,
// keyword resolution, ability AST dispatch, deck-building math).
//
// Loaded only by tests under __tests__/. Excluded from production
// bundles by Turborepo build outputs and the working-agreement rule
// in CLAUDE.md.

import { z } from 'zod';

// ────────────────────────────────────────────────────────────────────
// Enums (mirror @prophecy/protocol; duplicated here to keep fixtures
// loadable without protocol depending on game-engine for tests)
// ────────────────────────────────────────────────────────────────────

export const FactionSchema = z.enum(['light', 'shadow', 'neutral']);
export const ColorSchema = z.enum(['red', 'blue', 'yellow', 'gray']);
export const RaritySchema = z.enum(['fixed', 'common', 'uncommon', 'rare', 'legendary']);
export const CardTypeSchema = z.enum([
  'character',
  'upgrade',
  'support',
  'event',
  'plot',
  'battlefield',
]);
export const DieSymbolSchema = z.enum([
  'melee',
  'ranged',
  'indirect',
  'shield',
  'resource',
  'disrupt',
  'discard',
  'focus',
  'special',
  'blank',
]);
export const KeywordSchema = z.enum(['ambush', 'guardian', 'modify', 'redeploy']);

export const DieFaceSchema = z.object({
  symbol: DieSymbolSchema,
  value: z.number().int().min(0).max(10),
  cost: z.number().int().min(0).max(5),
  modifier: z.boolean(),
});

// ────────────────────────────────────────────────────────────────────
// AbilityAst — abstract templates for engine ability resolvers.
// Each variant maps to a pattern common to dice-and-card TCGs (after
// triggers, before/replacement effects, ongoing modifiers, keyword
// shorthands, special-die effects). Resolvers in the engine switch on
// `kind` and dispatch.
// ────────────────────────────────────────────────────────────────────

// Targets / subjects expressed as small enums so generators and the
// future resolver share a vocabulary.
export const TargetSchema = z.enum([
  'self',
  'self.character',
  'self.any-character',
  'opponent.character',
  'opponent.any-character',
  'any-character',
  'self.pool',
  'opponent.pool',
  'self.upgrade-dice',
]);

export const TriggerEventSchema = z.enum([
  'activate',
  'play-card',
  'damage-dealt',
  'character-defeated',
  'gain-shields',
  'claim-battlefield',
  'upkeep',
  'round-begin',
]);

export const TriggerSchema = z.object({
  event: TriggerEventSchema,
  subject: z.enum(['self', 'self.any', 'opponent.any', 'any']),
});

export const EffectSchema = z.discriminatedUnion('op', [
  z.object({ op: z.literal('deal-damage'), amount: z.number().int().min(1), target: TargetSchema }),
  z.object({ op: z.literal('gain-resources'), amount: z.number().int().min(1) }),
  z.object({ op: z.literal('lose-resources-opponent'), amount: z.number().int().min(1) }),
  z.object({ op: z.literal('gain-shields'), amount: z.number().int().min(1), target: TargetSchema }),
  z.object({ op: z.literal('heal'), amount: z.number().int().min(1), target: TargetSchema }),
  z.object({ op: z.literal('draw-cards'), amount: z.number().int().min(1) }),
  z.object({ op: z.literal('discard-cards-opponent'), amount: z.number().int().min(1) }),
  z.object({ op: z.literal('reroll-dice'), count: z.union([z.number().int().min(1), z.literal('any')]) }),
  z.object({ op: z.literal('remove-die'), from: z.enum(['opponent.pool', 'self.pool']) }),
  z.object({ op: z.literal('resolve-die'), from: z.enum(['self.pool', 'self.upgrade-dice']) }),
  z.object({ op: z.literal('ready-character'), target: TargetSchema }),
  z.object({ op: z.literal('exhaust-character'), target: TargetSchema }),
  z.object({ op: z.literal('turn-die'), count: z.number().int().min(1) }),
]);

export const CostSchema = z.discriminatedUnion('op', [
  z.object({ op: z.literal('spend-resources'), amount: z.number().int().min(1) }),
  z.object({ op: z.literal('exhaust-self') }),
  z.object({ op: z.literal('discard-card-from-hand') }),
]);

export const ConditionSchema = z.discriminatedUnion('op', [
  z.object({
    op: z.literal('spot'),
    element: z.enum([
      'character.faction.light',
      'character.faction.shadow',
      'character.color.red',
      'character.color.blue',
      'character.color.yellow',
      'character.color.gray',
    ]),
  }),
]);

export const AbilityAstSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('action'),
    cost: z.array(CostSchema).default([]),
    may: z.boolean().default(false),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('power-action'),
    cost: z.array(CostSchema).default([]),
    may: z.boolean().default(false),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('claim'),
    may: z.boolean().default(true),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('ongoing'),
    conditions: z.array(ConditionSchema).default([]),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('triggered.after'),
    trigger: TriggerSchema,
    conditions: z.array(ConditionSchema).default([]),
    may: z.boolean().default(false),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('triggered.before'),
    trigger: TriggerSchema,
    conditions: z.array(ConditionSchema).default([]),
    may: z.boolean().default(false),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('inherent.die'),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('special'),
    effect: z.array(EffectSchema).min(1),
  }),
  z.object({
    kind: z.literal('keyword'),
    keyword: KeywordSchema,
  }),
]);

// ────────────────────────────────────────────────────────────────────
// CardFixture — one entry per card in the synthetic set
// ────────────────────────────────────────────────────────────────────

/**
 * Subtypes are mythological groupings drawn from public-domain Greek
 * and Norse sources. Same five for the v1 corpus; expand to other
 * pantheons (Egyptian, Hindu, Mesopotamian, ...) later.
 */
export const SubtypeSchema = z.enum(['Olympian', 'Aesir', 'Vanir', 'Titan', 'Giant']);

export const CardFixtureSchema = z
  .object({
    id: z.string().regex(/^[A-Z]+_[0-9]{3}$/),
    /**
     * Card title — v1 uses public-domain Greek + Norse mythological
     * names (gods, heroes, artifacts, places, events) so the synthetic
     * set feels like real content while staying clear of any
     * third-party copyright.
     */
    title: z.string().min(1).max(60),
    type: CardTypeSchema,
    faction: FactionSchema,
    color: ColorSchema,
    rarity: RaritySchema,
    /** Cost to play (events / upgrades / supports). null for characters and battlefields. */
    cost: z.number().int().min(0).max(8).nullable(),
    /** Health (characters only). */
    health: z.number().int().min(1).max(20).nullable(),
    /** Non-elite point value (characters). null for plots' negative-value case handled separately. */
    pointValue: z.number().int().min(1).max(25).nullable(),
    /** Elite point value (characters with 2 dice). */
    elitePointValue: z.number().int().min(1).max(35).nullable(),
    /** Plot point cost; usually 0 or negative. */
    plotPointValue: z.number().int().min(-3).max(3).nullable(),
    isUnique: z.boolean(),
    subtypes: z.array(SubtypeSchema).max(3),
    /** Six die faces (characters / dice-bearing upgrades / supports). null otherwise. */
    dieFaces: z
      .tuple([DieFaceSchema, DieFaceSchema, DieFaceSchema, DieFaceSchema, DieFaceSchema, DieFaceSchema])
      .nullable(),
    /** Ability list — empty for cards with no abilities. */
    abilities: z.array(AbilityAstSchema),
  })
  .strict();

export type CardFixture = z.infer<typeof CardFixtureSchema>;
export type AbilityAst = z.infer<typeof AbilityAstSchema>;
export type EffectAst = z.infer<typeof EffectSchema>;
export type TriggerAst = z.infer<typeof TriggerSchema>;
export type CostAst = z.infer<typeof CostSchema>;
export type ConditionAst = z.infer<typeof ConditionSchema>;

export const CardSetSchema = z.object({
  version: z.string(),
  generatedAt: z.string(),
  seed: z.string(),
  cards: z.array(CardFixtureSchema).min(100),
});
export type CardSet = z.infer<typeof CardSetSchema>;
